FROM mcr.microsoft.com/java/maven:8-zulu-debian9

LABEL maintainer="auri@ufscar.br, g4briel.4lves@gmail.com"

COPY mvn-entrypoint.sh /usr/local/bin/mvn-entrypoint.sh
RUN chmod a+x /usr/local/bin/mvn-entrypoint.sh